/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "background": "#f8f9ff",
        "on-background": "#121c2a",
        "surface": "#f8f9ff",
        "on-surface": "#121c2a",
        "surface-variant": "#d9e3f6",
        "on-surface-variant": "#3c4a42",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e6eeff",
        "surface-container-high": "#dee9fc",
        "surface-container-highest": "#d9e3f6",
        "surface-dim": "#d0dbed",
        "surface-bright": "#f8f9ff",
        "surface-tint": "#006c49",
        "primary": "#006c49",
        "on-primary": "#ffffff",
        "primary-container": "#10b981",
        "on-primary-container": "#00422b",
        "primary-fixed": "#6ffbbe",
        "on-primary-fixed": "#002113",
        "primary-fixed-dim": "#4edea3",
        "on-primary-fixed-variant": "#005236",
        "inverse-primary": "#4edea3",
        "secondary": "#5d5f5f",
        "on-secondary": "#ffffff",
        "secondary-container": "#dfe0e0",
        "on-secondary-container": "#616363",
        "secondary-fixed": "#e2e2e2",
        "on-secondary-fixed": "#1a1c1c",
        "secondary-fixed-dim": "#c6c6c7",
        "on-secondary-fixed-variant": "#454747",
        "tertiary": "#a43a3a",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#fc7c78",
        "on-tertiary-container": "#711419",
        "tertiary-fixed": "#ffdad7",
        "on-tertiary-fixed": "#410005",
        "tertiary-fixed-dim": "#ffb3af",
        "on-tertiary-fixed-variant": "#842225",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "outline": "#6c7a71",
        "outline-variant": "#bbcabf",
        "inverse-surface": "#27313f",
        "inverse-on-surface": "#eaf1ff"
      },
      spacing: {
        "gutter": "1.5rem",
        "stack-sm": "0.5rem",
        "stack-md": "1rem",
        "stack-lg": "2rem",
        "margin-page": "2rem",
        "sidebar-width": "280px",
        "container-max": "1440px"
      },
      fontFamily: {
        "headline-md": ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}